# Generated by Django 3.2.8 on 2021-10-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['title'], 'verbose_name_plural': 'Blog'},
        ),
    ]
